// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: erc721/v1/erc721.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetERC721BalanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	OwnerAddress    string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Address to query balance for
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721BalanceRequest) Reset() {
	*x = GetERC721BalanceRequest{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721BalanceRequest) ProtoMessage() {}

func (x *GetERC721BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721BalanceRequest.ProtoReflect.Descriptor instead.
func (*GetERC721BalanceRequest) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{0}
}

func (x *GetERC721BalanceRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721BalanceRequest) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

type GetERC721BalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Balance         string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`                                        // Number of NFTs owned
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	OwnerAddress    string                 `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721BalanceResponse) Reset() {
	*x = GetERC721BalanceResponse{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721BalanceResponse) ProtoMessage() {}

func (x *GetERC721BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721BalanceResponse.ProtoReflect.Descriptor instead.
func (*GetERC721BalanceResponse) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{1}
}

func (x *GetERC721BalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetERC721BalanceResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721BalanceResponse) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

type GetERC721TokenInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721TokenInfoRequest) Reset() {
	*x = GetERC721TokenInfoRequest{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721TokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721TokenInfoRequest) ProtoMessage() {}

func (x *GetERC721TokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721TokenInfoRequest.ProtoReflect.Descriptor instead.
func (*GetERC721TokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{2}
}

func (x *GetERC721TokenInfoRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type GetERC721TokenInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                              // Token name
	Symbol          string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                          // Token symbol
	ContractAddress string                 `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721TokenInfoResponse) Reset() {
	*x = GetERC721TokenInfoResponse{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721TokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721TokenInfoResponse) ProtoMessage() {}

func (x *GetERC721TokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721TokenInfoResponse.ProtoReflect.Descriptor instead.
func (*GetERC721TokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{3}
}

func (x *GetERC721TokenInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetERC721TokenInfoResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetERC721TokenInfoResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type GetERC721TokenURIRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string to handle large numbers)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721TokenURIRequest) Reset() {
	*x = GetERC721TokenURIRequest{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721TokenURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721TokenURIRequest) ProtoMessage() {}

func (x *GetERC721TokenURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721TokenURIRequest.ProtoReflect.Descriptor instead.
func (*GetERC721TokenURIRequest) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{4}
}

func (x *GetERC721TokenURIRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721TokenURIRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC721TokenURIResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenUri        string                 `protobuf:"bytes,1,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`                      // Token URI (metadata)
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721TokenURIResponse) Reset() {
	*x = GetERC721TokenURIResponse{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721TokenURIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721TokenURIResponse) ProtoMessage() {}

func (x *GetERC721TokenURIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721TokenURIResponse.ProtoReflect.Descriptor instead.
func (*GetERC721TokenURIResponse) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{5}
}

func (x *GetERC721TokenURIResponse) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *GetERC721TokenURIResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721TokenURIResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC721OwnerOfRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string to handle large numbers)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721OwnerOfRequest) Reset() {
	*x = GetERC721OwnerOfRequest{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721OwnerOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721OwnerOfRequest) ProtoMessage() {}

func (x *GetERC721OwnerOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721OwnerOfRequest.ProtoReflect.Descriptor instead.
func (*GetERC721OwnerOfRequest) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{6}
}

func (x *GetERC721OwnerOfRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721OwnerOfRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC721OwnerOfResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721OwnerOfResponse) Reset() {
	*x = GetERC721OwnerOfResponse{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721OwnerOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721OwnerOfResponse) ProtoMessage() {}

func (x *GetERC721OwnerOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721OwnerOfResponse.ProtoReflect.Descriptor instead.
func (*GetERC721OwnerOfResponse) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{7}
}

func (x *GetERC721OwnerOfResponse) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *GetERC721OwnerOfResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721OwnerOfResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC721ApprovedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string to handle large numbers)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721ApprovedRequest) Reset() {
	*x = GetERC721ApprovedRequest{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721ApprovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721ApprovedRequest) ProtoMessage() {}

func (x *GetERC721ApprovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721ApprovedRequest.ProtoReflect.Descriptor instead.
func (*GetERC721ApprovedRequest) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{8}
}

func (x *GetERC721ApprovedRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721ApprovedRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC721ApprovedResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApprovedAddress string                 `protobuf:"bytes,1,opt,name=approved_address,json=approvedAddress,proto3" json:"approved_address,omitempty"` // Approved address (or zero address if none)
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC721ApprovedResponse) Reset() {
	*x = GetERC721ApprovedResponse{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC721ApprovedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC721ApprovedResponse) ProtoMessage() {}

func (x *GetERC721ApprovedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC721ApprovedResponse.ProtoReflect.Descriptor instead.
func (*GetERC721ApprovedResponse) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{9}
}

func (x *GetERC721ApprovedResponse) GetApprovedAddress() string {
	if x != nil {
		return x.ApprovedAddress
	}
	return ""
}

func (x *GetERC721ApprovedResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC721ApprovedResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type IsApprovedForAllERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	OwnerAddress    string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	OperatorAddress string                 `protobuf:"bytes,3,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsApprovedForAllERC721Request) Reset() {
	*x = IsApprovedForAllERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsApprovedForAllERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApprovedForAllERC721Request) ProtoMessage() {}

func (x *IsApprovedForAllERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApprovedForAllERC721Request.ProtoReflect.Descriptor instead.
func (*IsApprovedForAllERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{10}
}

func (x *IsApprovedForAllERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *IsApprovedForAllERC721Request) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *IsApprovedForAllERC721Request) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

type IsApprovedForAllERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Approved        bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`                                     // Whether operator is approved for all tokens
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	OwnerAddress    string                 `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	OperatorAddress string                 `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsApprovedForAllERC721Response) Reset() {
	*x = IsApprovedForAllERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsApprovedForAllERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApprovedForAllERC721Response) ProtoMessage() {}

func (x *IsApprovedForAllERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApprovedForAllERC721Response.ProtoReflect.Descriptor instead.
func (*IsApprovedForAllERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{11}
}

func (x *IsApprovedForAllERC721Response) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *IsApprovedForAllERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *IsApprovedForAllERC721Response) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *IsApprovedForAllERC721Response) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

type TransferERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	FromAddress     string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // Current owner address (must match private key)
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Recipient address
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID to transfer (as string)
	PrivateKey      string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferERC721Request) Reset() {
	*x = TransferERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferERC721Request) ProtoMessage() {}

func (x *TransferERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferERC721Request.ProtoReflect.Descriptor instead.
func (*TransferERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{12}
}

func (x *TransferERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *TransferERC721Request) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransferERC721Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferERC721Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TransferERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type TransferERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	FromAddress     string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // From address
	ToAddress       string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // To address
	TokenId         string                 `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferERC721Response) Reset() {
	*x = TransferERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferERC721Response) ProtoMessage() {}

func (x *TransferERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferERC721Response.ProtoReflect.Descriptor instead.
func (*TransferERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{13}
}

func (x *TransferERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransferERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *TransferERC721Response) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransferERC721Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferERC721Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type SafeTransferERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	FromAddress     string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // Current owner address (must match private key)
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Recipient address
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID to transfer (as string)
	PrivateKey      string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeTransferERC721Request) Reset() {
	*x = SafeTransferERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeTransferERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeTransferERC721Request) ProtoMessage() {}

func (x *SafeTransferERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeTransferERC721Request.ProtoReflect.Descriptor instead.
func (*SafeTransferERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{14}
}

func (x *SafeTransferERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeTransferERC721Request) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeTransferERC721Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeTransferERC721Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SafeTransferERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SafeTransferERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	FromAddress     string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // From address
	ToAddress       string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // To address
	TokenId         string                 `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeTransferERC721Response) Reset() {
	*x = SafeTransferERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeTransferERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeTransferERC721Response) ProtoMessage() {}

func (x *SafeTransferERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeTransferERC721Response.ProtoReflect.Descriptor instead.
func (*SafeTransferERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{15}
}

func (x *SafeTransferERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SafeTransferERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeTransferERC721Response) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeTransferERC721Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeTransferERC721Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type SafeTransferERC721WithDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	FromAddress     string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // Current owner address (must match private key)
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Recipient address
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID to transfer (as string)
	Data            []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                              // Additional data to send with transfer
	PrivateKey      string                 `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeTransferERC721WithDataRequest) Reset() {
	*x = SafeTransferERC721WithDataRequest{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeTransferERC721WithDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeTransferERC721WithDataRequest) ProtoMessage() {}

func (x *SafeTransferERC721WithDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeTransferERC721WithDataRequest.ProtoReflect.Descriptor instead.
func (*SafeTransferERC721WithDataRequest) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{16}
}

func (x *SafeTransferERC721WithDataRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeTransferERC721WithDataRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeTransferERC721WithDataRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeTransferERC721WithDataRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SafeTransferERC721WithDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SafeTransferERC721WithDataRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SafeTransferERC721WithDataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	FromAddress     string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // From address
	ToAddress       string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // To address
	TokenId         string                 `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeTransferERC721WithDataResponse) Reset() {
	*x = SafeTransferERC721WithDataResponse{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeTransferERC721WithDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeTransferERC721WithDataResponse) ProtoMessage() {}

func (x *SafeTransferERC721WithDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeTransferERC721WithDataResponse.ProtoReflect.Descriptor instead.
func (*SafeTransferERC721WithDataResponse) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{17}
}

func (x *SafeTransferERC721WithDataResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SafeTransferERC721WithDataResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeTransferERC721WithDataResponse) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeTransferERC721WithDataResponse) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeTransferERC721WithDataResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type ApproveERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	ApprovedAddress string                 `protobuf:"bytes,2,opt,name=approved_address,json=approvedAddress,proto3" json:"approved_address,omitempty"` // Address to approve
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID to approve
	PrivateKey      string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApproveERC721Request) Reset() {
	*x = ApproveERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveERC721Request) ProtoMessage() {}

func (x *ApproveERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveERC721Request.ProtoReflect.Descriptor instead.
func (*ApproveERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{18}
}

func (x *ApproveERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ApproveERC721Request) GetApprovedAddress() string {
	if x != nil {
		return x.ApprovedAddress
	}
	return ""
}

func (x *ApproveERC721Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ApproveERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type ApproveERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	OwnerAddress    string                 `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	ApprovedAddress string                 `protobuf:"bytes,4,opt,name=approved_address,json=approvedAddress,proto3" json:"approved_address,omitempty"` // Approved address
	TokenId         string                 `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApproveERC721Response) Reset() {
	*x = ApproveERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveERC721Response) ProtoMessage() {}

func (x *ApproveERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveERC721Response.ProtoReflect.Descriptor instead.
func (*ApproveERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{19}
}

func (x *ApproveERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ApproveERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ApproveERC721Response) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *ApproveERC721Response) GetApprovedAddress() string {
	if x != nil {
		return x.ApprovedAddress
	}
	return ""
}

func (x *ApproveERC721Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type SetApprovalForAllERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	OperatorAddress string                 `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	Approved        bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`                                     // Whether to approve or revoke approval
	PrivateKey      string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetApprovalForAllERC721Request) Reset() {
	*x = SetApprovalForAllERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetApprovalForAllERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovalForAllERC721Request) ProtoMessage() {}

func (x *SetApprovalForAllERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovalForAllERC721Request.ProtoReflect.Descriptor instead.
func (*SetApprovalForAllERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{20}
}

func (x *SetApprovalForAllERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SetApprovalForAllERC721Request) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

func (x *SetApprovalForAllERC721Request) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *SetApprovalForAllERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SetApprovalForAllERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	OwnerAddress    string                 `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	OperatorAddress string                 `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	Approved        bool                   `protobuf:"varint,5,opt,name=approved,proto3" json:"approved,omitempty"`                                     // Approval status set
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetApprovalForAllERC721Response) Reset() {
	*x = SetApprovalForAllERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetApprovalForAllERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovalForAllERC721Response) ProtoMessage() {}

func (x *SetApprovalForAllERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovalForAllERC721Response.ProtoReflect.Descriptor instead.
func (*SetApprovalForAllERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{21}
}

func (x *SetApprovalForAllERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SetApprovalForAllERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SetApprovalForAllERC721Response) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *SetApprovalForAllERC721Response) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

func (x *SetApprovalForAllERC721Response) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type SafeMintERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	ToAddress       string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Address to mint token to
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID to mint (as string)
	PrivateKey      string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeMintERC721Request) Reset() {
	*x = SafeMintERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeMintERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeMintERC721Request) ProtoMessage() {}

func (x *SafeMintERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeMintERC721Request.ProtoReflect.Descriptor instead.
func (*SafeMintERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{22}
}

func (x *SafeMintERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeMintERC721Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeMintERC721Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SafeMintERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SafeMintERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Address that received minted token
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID minted
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeMintERC721Response) Reset() {
	*x = SafeMintERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeMintERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeMintERC721Response) ProtoMessage() {}

func (x *SafeMintERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeMintERC721Response.ProtoReflect.Descriptor instead.
func (*SafeMintERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{23}
}

func (x *SafeMintERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SafeMintERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeMintERC721Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeMintERC721Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type BurnERC721Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC721 contract address
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID to burn (as string)
	PrivateKey      string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnERC721Request) Reset() {
	*x = BurnERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnERC721Request) ProtoMessage() {}

func (x *BurnERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnERC721Request.ProtoReflect.Descriptor instead.
func (*BurnERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{24}
}

func (x *BurnERC721Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BurnERC721Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *BurnERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type BurnERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID burned
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnERC721Response) Reset() {
	*x = BurnERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnERC721Response) ProtoMessage() {}

func (x *BurnERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnERC721Response.ProtoReflect.Descriptor instead.
func (*BurnERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{25}
}

func (x *BurnERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *BurnERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BurnERC721Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type DeployERC721Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // Token name
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                 // Token symbol
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`       // Private key of the deployer
	InitialOwner  string                 `protobuf:"bytes,4,opt,name=initial_owner,json=initialOwner,proto3" json:"initial_owner,omitempty"` // Initial owner address (optional, defaults to deployer)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployERC721Request) Reset() {
	*x = DeployERC721Request{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployERC721Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployERC721Request) ProtoMessage() {}

func (x *DeployERC721Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployERC721Request.ProtoReflect.Descriptor instead.
func (*DeployERC721Request) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{26}
}

func (x *DeployERC721Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployERC721Request) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DeployERC721Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *DeployERC721Request) GetInitialOwner() string {
	if x != nil {
		return x.InitialOwner
	}
	return ""
}

type DeployERC721Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Deployed contract address
	DeployerAddress string                 `protobuf:"bytes,3,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"` // Deployer address
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                              // Token name
	Symbol          string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`                                          // Token symbol
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployERC721Response) Reset() {
	*x = DeployERC721Response{}
	mi := &file_erc721_v1_erc721_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployERC721Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployERC721Response) ProtoMessage() {}

func (x *DeployERC721Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc721_v1_erc721_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployERC721Response.ProtoReflect.Descriptor instead.
func (*DeployERC721Response) Descriptor() ([]byte, []int) {
	return file_erc721_v1_erc721_proto_rawDescGZIP(), []int{27}
}

func (x *DeployERC721Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DeployERC721Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *DeployERC721Response) GetDeployerAddress() string {
	if x != nil {
		return x.DeployerAddress
	}
	return ""
}

func (x *DeployERC721Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployERC721Response) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_erc721_v1_erc721_proto protoreflect.FileDescriptor

const file_erc721_v1_erc721_proto_rawDesc = "" +
	"\n" +
	"\x16erc721/v1/erc721.proto\x12\rapi.erc721.v1\x1a\x1cgoogle/api/annotations.proto\"i\n" +
	"\x17GetERC721BalanceRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x02 \x01(\tR\fownerAddress\"\x84\x01\n" +
	"\x18GetERC721BalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x03 \x01(\tR\fownerAddress\"F\n" +
	"\x19GetERC721TokenInfoRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\"s\n" +
	"\x1aGetERC721TokenInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12)\n" +
	"\x10contract_address\x18\x03 \x01(\tR\x0fcontractAddress\"`\n" +
	"\x18GetERC721TokenURIRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"~\n" +
	"\x19GetERC721TokenURIResponse\x12\x1b\n" +
	"\ttoken_uri\x18\x01 \x01(\tR\btokenUri\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"_\n" +
	"\x17GetERC721OwnerOfRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"\x85\x01\n" +
	"\x18GetERC721OwnerOfResponse\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"`\n" +
	"\x18GetERC721ApprovedRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"\x8c\x01\n" +
	"\x19GetERC721ApprovedResponse\x12)\n" +
	"\x10approved_address\x18\x01 \x01(\tR\x0fapprovedAddress\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"\x9a\x01\n" +
	"\x1dIsApprovedForAllERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x02 \x01(\tR\fownerAddress\x12)\n" +
	"\x10operator_address\x18\x03 \x01(\tR\x0foperatorAddress\"\xb7\x01\n" +
	"\x1eIsApprovedForAllERC721Response\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x03 \x01(\tR\fownerAddress\x12)\n" +
	"\x10operator_address\x18\x04 \x01(\tR\x0foperatorAddress\"\xc0\x01\n" +
	"\x15TransferERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\"\xb9\x01\n" +
	"\x16TransferERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x05 \x01(\tR\atokenId\"\xc4\x01\n" +
	"\x19SafeTransferERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\"\xbd\x01\n" +
	"\x1aSafeTransferERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x05 \x01(\tR\atokenId\"\xe0\x01\n" +
	"!SafeTransferERC721WithDataRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\tR\n" +
	"privateKey\"\xc5\x01\n" +
	"\"SafeTransferERC721WithDataResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x05 \x01(\tR\atokenId\"\xa8\x01\n" +
	"\x14ApproveERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12)\n" +
	"\x10approved_address\x18\x02 \x01(\tR\x0fapprovedAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\"\xc6\x01\n" +
	"\x15ApproveERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x03 \x01(\tR\fownerAddress\x12)\n" +
	"\x10approved_address\x18\x04 \x01(\tR\x0fapprovedAddress\x12\x19\n" +
	"\btoken_id\x18\x05 \x01(\tR\atokenId\"\xb3\x01\n" +
	"\x1eSetApprovalForAllERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12)\n" +
	"\x10operator_address\x18\x02 \x01(\tR\x0foperatorAddress\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\"\xd1\x01\n" +
	"\x1fSetApprovalForAllERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x03 \x01(\tR\fownerAddress\x12)\n" +
	"\x10operator_address\x18\x04 \x01(\tR\x0foperatorAddress\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\bR\bapproved\"\x9d\x01\n" +
	"\x15SafeMintERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\"\x96\x01\n" +
	"\x16SafeMintERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\"z\n" +
	"\x11BurnERC721Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\"s\n" +
	"\x12BurnERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"\x87\x01\n" +
	"\x13DeployERC721Request\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12#\n" +
	"\rinitial_owner\x18\x04 \x01(\tR\finitialOwner\"\xb1\x01\n" +
	"\x14DeployERC721Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12)\n" +
	"\x10deployer_address\x18\x03 \x01(\tR\x0fdeployerAddress\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol2\xc4\x0f\n" +
	"\x06ERC721\x12\x83\x01\n" +
	"\x10GetERC721Balance\x12&.api.erc721.v1.GetERC721BalanceRequest\x1a'.api.erc721.v1.GetERC721BalanceResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/erc721/balance\x12\x86\x01\n" +
	"\x12GetERC721TokenInfo\x12(.api.erc721.v1.GetERC721TokenInfoRequest\x1a).api.erc721.v1.GetERC721TokenInfoResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/erc721/info\x12\x88\x01\n" +
	"\x11GetERC721TokenURI\x12'.api.erc721.v1.GetERC721TokenURIRequest\x1a(.api.erc721.v1.GetERC721TokenURIResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/erc721/token-uri\x12\x84\x01\n" +
	"\x10GetERC721OwnerOf\x12&.api.erc721.v1.GetERC721OwnerOfRequest\x1a'.api.erc721.v1.GetERC721OwnerOfResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/erc721/owner-of\x12\x87\x01\n" +
	"\x11GetERC721Approved\x12'.api.erc721.v1.GetERC721ApprovedRequest\x1a(.api.erc721.v1.GetERC721ApprovedResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/erc721/approved\x12\xa1\x01\n" +
	"\x16IsApprovedForAllERC721\x12,.api.erc721.v1.IsApprovedForAllERC721Request\x1a-.api.erc721.v1.IsApprovedForAllERC721Response\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/erc721/is-approved-for-all\x12\x81\x01\n" +
	"\x0eTransferERC721\x12$.api.erc721.v1.TransferERC721Request\x1a%.api.erc721.v1.TransferERC721Response\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/erc721/transfer\x12\x92\x01\n" +
	"\x12SafeTransferERC721\x12(.api.erc721.v1.SafeTransferERC721Request\x1a).api.erc721.v1.SafeTransferERC721Response\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/erc721/safe-transfer\x12\xb4\x01\n" +
	"\x1aSafeTransferERC721WithData\x120.api.erc721.v1.SafeTransferERC721WithDataRequest\x1a1.api.erc721.v1.SafeTransferERC721WithDataResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/erc721/safe-transfer-with-data\x12}\n" +
	"\rApproveERC721\x12#.api.erc721.v1.ApproveERC721Request\x1a$.api.erc721.v1.ApproveERC721Response\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/erc721/approve\x12\xa8\x01\n" +
	"\x17SetApprovalForAllERC721\x12-.api.erc721.v1.SetApprovalForAllERC721Request\x1a..api.erc721.v1.SetApprovalForAllERC721Response\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/erc721/set-approval-for-all\x12\x82\x01\n" +
	"\x0eSafeMintERC721\x12$.api.erc721.v1.SafeMintERC721Request\x1a%.api.erc721.v1.SafeMintERC721Response\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/erc721/safe-mint\x12q\n" +
	"\n" +
	"BurnERC721\x12 .api.erc721.v1.BurnERC721Request\x1a!.api.erc721.v1.BurnERC721Response\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/erc721/burn\x12y\n" +
	"\fDeployERC721\x12\".api.erc721.v1.DeployERC721Request\x1a#.api.erc721.v1.DeployERC721Response\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/erc721/deployB8\n" +
	"\rapi.erc721.v1P\x01Z%eth-contract-service/api/erc721/v1;v1b\x06proto3"

var (
	file_erc721_v1_erc721_proto_rawDescOnce sync.Once
	file_erc721_v1_erc721_proto_rawDescData []byte
)

func file_erc721_v1_erc721_proto_rawDescGZIP() []byte {
	file_erc721_v1_erc721_proto_rawDescOnce.Do(func() {
		file_erc721_v1_erc721_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_erc721_v1_erc721_proto_rawDesc), len(file_erc721_v1_erc721_proto_rawDesc)))
	})
	return file_erc721_v1_erc721_proto_rawDescData
}

var file_erc721_v1_erc721_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_erc721_v1_erc721_proto_goTypes = []any{
	(*GetERC721BalanceRequest)(nil),            // 0: api.erc721.v1.GetERC721BalanceRequest
	(*GetERC721BalanceResponse)(nil),           // 1: api.erc721.v1.GetERC721BalanceResponse
	(*GetERC721TokenInfoRequest)(nil),          // 2: api.erc721.v1.GetERC721TokenInfoRequest
	(*GetERC721TokenInfoResponse)(nil),         // 3: api.erc721.v1.GetERC721TokenInfoResponse
	(*GetERC721TokenURIRequest)(nil),           // 4: api.erc721.v1.GetERC721TokenURIRequest
	(*GetERC721TokenURIResponse)(nil),          // 5: api.erc721.v1.GetERC721TokenURIResponse
	(*GetERC721OwnerOfRequest)(nil),            // 6: api.erc721.v1.GetERC721OwnerOfRequest
	(*GetERC721OwnerOfResponse)(nil),           // 7: api.erc721.v1.GetERC721OwnerOfResponse
	(*GetERC721ApprovedRequest)(nil),           // 8: api.erc721.v1.GetERC721ApprovedRequest
	(*GetERC721ApprovedResponse)(nil),          // 9: api.erc721.v1.GetERC721ApprovedResponse
	(*IsApprovedForAllERC721Request)(nil),      // 10: api.erc721.v1.IsApprovedForAllERC721Request
	(*IsApprovedForAllERC721Response)(nil),     // 11: api.erc721.v1.IsApprovedForAllERC721Response
	(*TransferERC721Request)(nil),              // 12: api.erc721.v1.TransferERC721Request
	(*TransferERC721Response)(nil),             // 13: api.erc721.v1.TransferERC721Response
	(*SafeTransferERC721Request)(nil),          // 14: api.erc721.v1.SafeTransferERC721Request
	(*SafeTransferERC721Response)(nil),         // 15: api.erc721.v1.SafeTransferERC721Response
	(*SafeTransferERC721WithDataRequest)(nil),  // 16: api.erc721.v1.SafeTransferERC721WithDataRequest
	(*SafeTransferERC721WithDataResponse)(nil), // 17: api.erc721.v1.SafeTransferERC721WithDataResponse
	(*ApproveERC721Request)(nil),               // 18: api.erc721.v1.ApproveERC721Request
	(*ApproveERC721Response)(nil),              // 19: api.erc721.v1.ApproveERC721Response
	(*SetApprovalForAllERC721Request)(nil),     // 20: api.erc721.v1.SetApprovalForAllERC721Request
	(*SetApprovalForAllERC721Response)(nil),    // 21: api.erc721.v1.SetApprovalForAllERC721Response
	(*SafeMintERC721Request)(nil),              // 22: api.erc721.v1.SafeMintERC721Request
	(*SafeMintERC721Response)(nil),             // 23: api.erc721.v1.SafeMintERC721Response
	(*BurnERC721Request)(nil),                  // 24: api.erc721.v1.BurnERC721Request
	(*BurnERC721Response)(nil),                 // 25: api.erc721.v1.BurnERC721Response
	(*DeployERC721Request)(nil),                // 26: api.erc721.v1.DeployERC721Request
	(*DeployERC721Response)(nil),               // 27: api.erc721.v1.DeployERC721Response
}
var file_erc721_v1_erc721_proto_depIdxs = []int32{
	0,  // 0: api.erc721.v1.ERC721.GetERC721Balance:input_type -> api.erc721.v1.GetERC721BalanceRequest
	2,  // 1: api.erc721.v1.ERC721.GetERC721TokenInfo:input_type -> api.erc721.v1.GetERC721TokenInfoRequest
	4,  // 2: api.erc721.v1.ERC721.GetERC721TokenURI:input_type -> api.erc721.v1.GetERC721TokenURIRequest
	6,  // 3: api.erc721.v1.ERC721.GetERC721OwnerOf:input_type -> api.erc721.v1.GetERC721OwnerOfRequest
	8,  // 4: api.erc721.v1.ERC721.GetERC721Approved:input_type -> api.erc721.v1.GetERC721ApprovedRequest
	10, // 5: api.erc721.v1.ERC721.IsApprovedForAllERC721:input_type -> api.erc721.v1.IsApprovedForAllERC721Request
	12, // 6: api.erc721.v1.ERC721.TransferERC721:input_type -> api.erc721.v1.TransferERC721Request
	14, // 7: api.erc721.v1.ERC721.SafeTransferERC721:input_type -> api.erc721.v1.SafeTransferERC721Request
	16, // 8: api.erc721.v1.ERC721.SafeTransferERC721WithData:input_type -> api.erc721.v1.SafeTransferERC721WithDataRequest
	18, // 9: api.erc721.v1.ERC721.ApproveERC721:input_type -> api.erc721.v1.ApproveERC721Request
	20, // 10: api.erc721.v1.ERC721.SetApprovalForAllERC721:input_type -> api.erc721.v1.SetApprovalForAllERC721Request
	22, // 11: api.erc721.v1.ERC721.SafeMintERC721:input_type -> api.erc721.v1.SafeMintERC721Request
	24, // 12: api.erc721.v1.ERC721.BurnERC721:input_type -> api.erc721.v1.BurnERC721Request
	26, // 13: api.erc721.v1.ERC721.DeployERC721:input_type -> api.erc721.v1.DeployERC721Request
	1,  // 14: api.erc721.v1.ERC721.GetERC721Balance:output_type -> api.erc721.v1.GetERC721BalanceResponse
	3,  // 15: api.erc721.v1.ERC721.GetERC721TokenInfo:output_type -> api.erc721.v1.GetERC721TokenInfoResponse
	5,  // 16: api.erc721.v1.ERC721.GetERC721TokenURI:output_type -> api.erc721.v1.GetERC721TokenURIResponse
	7,  // 17: api.erc721.v1.ERC721.GetERC721OwnerOf:output_type -> api.erc721.v1.GetERC721OwnerOfResponse
	9,  // 18: api.erc721.v1.ERC721.GetERC721Approved:output_type -> api.erc721.v1.GetERC721ApprovedResponse
	11, // 19: api.erc721.v1.ERC721.IsApprovedForAllERC721:output_type -> api.erc721.v1.IsApprovedForAllERC721Response
	13, // 20: api.erc721.v1.ERC721.TransferERC721:output_type -> api.erc721.v1.TransferERC721Response
	15, // 21: api.erc721.v1.ERC721.SafeTransferERC721:output_type -> api.erc721.v1.SafeTransferERC721Response
	17, // 22: api.erc721.v1.ERC721.SafeTransferERC721WithData:output_type -> api.erc721.v1.SafeTransferERC721WithDataResponse
	19, // 23: api.erc721.v1.ERC721.ApproveERC721:output_type -> api.erc721.v1.ApproveERC721Response
	21, // 24: api.erc721.v1.ERC721.SetApprovalForAllERC721:output_type -> api.erc721.v1.SetApprovalForAllERC721Response
	23, // 25: api.erc721.v1.ERC721.SafeMintERC721:output_type -> api.erc721.v1.SafeMintERC721Response
	25, // 26: api.erc721.v1.ERC721.BurnERC721:output_type -> api.erc721.v1.BurnERC721Response
	27, // 27: api.erc721.v1.ERC721.DeployERC721:output_type -> api.erc721.v1.DeployERC721Response
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_erc721_v1_erc721_proto_init() }
func file_erc721_v1_erc721_proto_init() {
	if File_erc721_v1_erc721_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_erc721_v1_erc721_proto_rawDesc), len(file_erc721_v1_erc721_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_erc721_v1_erc721_proto_goTypes,
		DependencyIndexes: file_erc721_v1_erc721_proto_depIdxs,
		MessageInfos:      file_erc721_v1_erc721_proto_msgTypes,
	}.Build()
	File_erc721_v1_erc721_proto = out.File
	file_erc721_v1_erc721_proto_goTypes = nil
	file_erc721_v1_erc721_proto_depIdxs = nil
}
