// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: erc1155/v1/erc1155.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetERC1155BalanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	AccountAddress  string                 `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account address to query balance for
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string to handle large numbers)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC1155BalanceRequest) Reset() {
	*x = GetERC1155BalanceRequest{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC1155BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC1155BalanceRequest) ProtoMessage() {}

func (x *GetERC1155BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC1155BalanceRequest.ProtoReflect.Descriptor instead.
func (*GetERC1155BalanceRequest) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{0}
}

func (x *GetERC1155BalanceRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC1155BalanceRequest) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *GetERC1155BalanceRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC1155BalanceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Balance         string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`                                        // Token balance (as string to handle large numbers)
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	AccountAddress  string                 `protobuf:"bytes,3,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account address
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC1155BalanceResponse) Reset() {
	*x = GetERC1155BalanceResponse{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC1155BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC1155BalanceResponse) ProtoMessage() {}

func (x *GetERC1155BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC1155BalanceResponse.ProtoReflect.Descriptor instead.
func (*GetERC1155BalanceResponse) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{1}
}

func (x *GetERC1155BalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetERC1155BalanceResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC1155BalanceResponse) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *GetERC1155BalanceResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC1155BalancesBatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	Accounts        []string               `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`                                      // List of account addresses
	TokenIds        []string               `protobuf:"bytes,3,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // List of token IDs (as string)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC1155BalancesBatchRequest) Reset() {
	*x = GetERC1155BalancesBatchRequest{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC1155BalancesBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC1155BalancesBatchRequest) ProtoMessage() {}

func (x *GetERC1155BalancesBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC1155BalancesBatchRequest.ProtoReflect.Descriptor instead.
func (*GetERC1155BalancesBatchRequest) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{2}
}

func (x *GetERC1155BalancesBatchRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC1155BalancesBatchRequest) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *GetERC1155BalancesBatchRequest) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type GetERC1155BalancesBatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Balances        []string               `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`                                      // List of balances (as string)
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	Accounts        []string               `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`                                      // Account addresses
	TokenIds        []string               `protobuf:"bytes,4,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // Token IDs
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC1155BalancesBatchResponse) Reset() {
	*x = GetERC1155BalancesBatchResponse{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC1155BalancesBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC1155BalancesBatchResponse) ProtoMessage() {}

func (x *GetERC1155BalancesBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC1155BalancesBatchResponse.ProtoReflect.Descriptor instead.
func (*GetERC1155BalancesBatchResponse) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{3}
}

func (x *GetERC1155BalancesBatchResponse) GetBalances() []string {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *GetERC1155BalancesBatchResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC1155BalancesBatchResponse) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *GetERC1155BalancesBatchResponse) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

type GetERC1155TokenURIRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	TokenId         string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string to handle large numbers)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC1155TokenURIRequest) Reset() {
	*x = GetERC1155TokenURIRequest{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC1155TokenURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC1155TokenURIRequest) ProtoMessage() {}

func (x *GetERC1155TokenURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC1155TokenURIRequest.ProtoReflect.Descriptor instead.
func (*GetERC1155TokenURIRequest) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{4}
}

func (x *GetERC1155TokenURIRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC1155TokenURIRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetERC1155TokenURIResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenUri        string                 `protobuf:"bytes,1,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`                      // Token URI (metadata)
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetERC1155TokenURIResponse) Reset() {
	*x = GetERC1155TokenURIResponse{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetERC1155TokenURIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetERC1155TokenURIResponse) ProtoMessage() {}

func (x *GetERC1155TokenURIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetERC1155TokenURIResponse.ProtoReflect.Descriptor instead.
func (*GetERC1155TokenURIResponse) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{5}
}

func (x *GetERC1155TokenURIResponse) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *GetERC1155TokenURIResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *GetERC1155TokenURIResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type IsApprovedForAllERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	AccountAddress  string                 `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account/Owner address
	OperatorAddress string                 `protobuf:"bytes,3,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsApprovedForAllERC1155Request) Reset() {
	*x = IsApprovedForAllERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsApprovedForAllERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApprovedForAllERC1155Request) ProtoMessage() {}

func (x *IsApprovedForAllERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApprovedForAllERC1155Request.ProtoReflect.Descriptor instead.
func (*IsApprovedForAllERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{6}
}

func (x *IsApprovedForAllERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *IsApprovedForAllERC1155Request) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *IsApprovedForAllERC1155Request) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

type IsApprovedForAllERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Approved        bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`                                     // Whether operator is approved for all tokens
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	AccountAddress  string                 `protobuf:"bytes,3,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account/Owner address
	OperatorAddress string                 `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsApprovedForAllERC1155Response) Reset() {
	*x = IsApprovedForAllERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsApprovedForAllERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApprovedForAllERC1155Response) ProtoMessage() {}

func (x *IsApprovedForAllERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApprovedForAllERC1155Response.ProtoReflect.Descriptor instead.
func (*IsApprovedForAllERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{7}
}

func (x *IsApprovedForAllERC1155Response) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *IsApprovedForAllERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *IsApprovedForAllERC1155Response) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *IsApprovedForAllERC1155Response) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

type SafeTransferERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	FromAddress     string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // Current owner address (must match private key)
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Recipient address
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string)
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                                          // Amount to transfer (as string)
	Data            []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                              // Additional data (can be empty)
	PrivateKey      string                 `protobuf:"bytes,7,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeTransferERC1155Request) Reset() {
	*x = SafeTransferERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeTransferERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeTransferERC1155Request) ProtoMessage() {}

func (x *SafeTransferERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeTransferERC1155Request.ProtoReflect.Descriptor instead.
func (*SafeTransferERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{8}
}

func (x *SafeTransferERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeTransferERC1155Request) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeTransferERC1155Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeTransferERC1155Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SafeTransferERC1155Request) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SafeTransferERC1155Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SafeTransferERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SafeTransferERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	FromAddress     string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // From address
	ToAddress       string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // To address
	TokenId         string                 `protobuf:"bytes,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	Amount          string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`                                          // Amount transferred
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeTransferERC1155Response) Reset() {
	*x = SafeTransferERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeTransferERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeTransferERC1155Response) ProtoMessage() {}

func (x *SafeTransferERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeTransferERC1155Response.ProtoReflect.Descriptor instead.
func (*SafeTransferERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{9}
}

func (x *SafeTransferERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SafeTransferERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeTransferERC1155Response) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeTransferERC1155Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeTransferERC1155Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SafeTransferERC1155Response) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SafeBatchTransferERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	FromAddress     string                 `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // Current owner address (must match private key)
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Recipient address
	TokenIds        []string               `protobuf:"bytes,4,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // List of token IDs (as string)
	Amounts         []string               `protobuf:"bytes,5,rep,name=amounts,proto3" json:"amounts,omitempty"`                                        // List of amounts (as string)
	Data            []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                              // Additional data (can be empty)
	PrivateKey      string                 `protobuf:"bytes,7,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeBatchTransferERC1155Request) Reset() {
	*x = SafeBatchTransferERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeBatchTransferERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeBatchTransferERC1155Request) ProtoMessage() {}

func (x *SafeBatchTransferERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeBatchTransferERC1155Request.ProtoReflect.Descriptor instead.
func (*SafeBatchTransferERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{10}
}

func (x *SafeBatchTransferERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeBatchTransferERC1155Request) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeBatchTransferERC1155Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeBatchTransferERC1155Request) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *SafeBatchTransferERC1155Request) GetAmounts() []string {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *SafeBatchTransferERC1155Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SafeBatchTransferERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SafeBatchTransferERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	FromAddress     string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`             // From address
	ToAddress       string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // To address
	TokenIds        []string               `protobuf:"bytes,5,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // Token IDs
	Amounts         []string               `protobuf:"bytes,6,rep,name=amounts,proto3" json:"amounts,omitempty"`                                        // Amounts transferred
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SafeBatchTransferERC1155Response) Reset() {
	*x = SafeBatchTransferERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeBatchTransferERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeBatchTransferERC1155Response) ProtoMessage() {}

func (x *SafeBatchTransferERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeBatchTransferERC1155Response.ProtoReflect.Descriptor instead.
func (*SafeBatchTransferERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{11}
}

func (x *SafeBatchTransferERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SafeBatchTransferERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SafeBatchTransferERC1155Response) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SafeBatchTransferERC1155Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SafeBatchTransferERC1155Response) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *SafeBatchTransferERC1155Response) GetAmounts() []string {
	if x != nil {
		return x.Amounts
	}
	return nil
}

type SetApprovalForAllERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	OperatorAddress string                 `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	Approved        bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`                                     // Whether to approve or revoke approval
	PrivateKey      string                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetApprovalForAllERC1155Request) Reset() {
	*x = SetApprovalForAllERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetApprovalForAllERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovalForAllERC1155Request) ProtoMessage() {}

func (x *SetApprovalForAllERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovalForAllERC1155Request.ProtoReflect.Descriptor instead.
func (*SetApprovalForAllERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{12}
}

func (x *SetApprovalForAllERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SetApprovalForAllERC1155Request) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

func (x *SetApprovalForAllERC1155Request) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *SetApprovalForAllERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type SetApprovalForAllERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	OwnerAddress    string                 `protobuf:"bytes,3,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // Owner address
	OperatorAddress string                 `protobuf:"bytes,4,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"` // Operator address
	Approved        bool                   `protobuf:"varint,5,opt,name=approved,proto3" json:"approved,omitempty"`                                     // Approval status set
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetApprovalForAllERC1155Response) Reset() {
	*x = SetApprovalForAllERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetApprovalForAllERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovalForAllERC1155Response) ProtoMessage() {}

func (x *SetApprovalForAllERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovalForAllERC1155Response.ProtoReflect.Descriptor instead.
func (*SetApprovalForAllERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{13}
}

func (x *SetApprovalForAllERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SetApprovalForAllERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *SetApprovalForAllERC1155Response) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *SetApprovalForAllERC1155Response) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

func (x *SetApprovalForAllERC1155Response) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type MintERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	ToAddress       string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Address to mint tokens to
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string)
	Amount          string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                          // Amount to mint (as string)
	Data            []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                              // Additional data (can be empty)
	PrivateKey      string                 `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MintERC1155Request) Reset() {
	*x = MintERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintERC1155Request) ProtoMessage() {}

func (x *MintERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintERC1155Request.ProtoReflect.Descriptor instead.
func (*MintERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{14}
}

func (x *MintERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *MintERC1155Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MintERC1155Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *MintERC1155Request) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MintERC1155Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MintERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type MintERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Address that received minted tokens
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                                          // Amount minted
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MintERC1155Response) Reset() {
	*x = MintERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintERC1155Response) ProtoMessage() {}

func (x *MintERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintERC1155Response.ProtoReflect.Descriptor instead.
func (*MintERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{15}
}

func (x *MintERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MintERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *MintERC1155Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MintERC1155Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *MintERC1155Response) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MintBatchERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	ToAddress       string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Address to mint tokens to
	TokenIds        []string               `protobuf:"bytes,3,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // List of token IDs (as string)
	Amounts         []string               `protobuf:"bytes,4,rep,name=amounts,proto3" json:"amounts,omitempty"`                                        // List of amounts (as string)
	Data            []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                              // Additional data (can be empty)
	PrivateKey      string                 `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MintBatchERC1155Request) Reset() {
	*x = MintBatchERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintBatchERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintBatchERC1155Request) ProtoMessage() {}

func (x *MintBatchERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintBatchERC1155Request.ProtoReflect.Descriptor instead.
func (*MintBatchERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{16}
}

func (x *MintBatchERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *MintBatchERC1155Request) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MintBatchERC1155Request) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *MintBatchERC1155Request) GetAmounts() []string {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *MintBatchERC1155Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MintBatchERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type MintBatchERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // Address that received minted tokens
	TokenIds        []string               `protobuf:"bytes,4,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // Token IDs
	Amounts         []string               `protobuf:"bytes,5,rep,name=amounts,proto3" json:"amounts,omitempty"`                                        // Amounts minted
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MintBatchERC1155Response) Reset() {
	*x = MintBatchERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintBatchERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintBatchERC1155Response) ProtoMessage() {}

func (x *MintBatchERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintBatchERC1155Response.ProtoReflect.Descriptor instead.
func (*MintBatchERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{17}
}

func (x *MintBatchERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *MintBatchERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *MintBatchERC1155Response) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MintBatchERC1155Response) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *MintBatchERC1155Response) GetAmounts() []string {
	if x != nil {
		return x.Amounts
	}
	return nil
}

type BurnERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	AccountAddress  string                 `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account address to burn from (must match private key)
	TokenId         string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID (as string)
	Amount          string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                          // Amount to burn (as string)
	PrivateKey      string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnERC1155Request) Reset() {
	*x = BurnERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnERC1155Request) ProtoMessage() {}

func (x *BurnERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnERC1155Request.ProtoReflect.Descriptor instead.
func (*BurnERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{18}
}

func (x *BurnERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BurnERC1155Request) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *BurnERC1155Request) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *BurnERC1155Request) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BurnERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type BurnERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	AccountAddress  string                 `protobuf:"bytes,3,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account address
	TokenId         string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                         // Token ID
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                                          // Amount burned
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnERC1155Response) Reset() {
	*x = BurnERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnERC1155Response) ProtoMessage() {}

func (x *BurnERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnERC1155Response.ProtoReflect.Descriptor instead.
func (*BurnERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{19}
}

func (x *BurnERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *BurnERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BurnERC1155Response) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *BurnERC1155Response) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *BurnERC1155Response) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type BurnBatchERC1155Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // ERC1155 contract address
	AccountAddress  string                 `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account address to burn from (must match private key)
	TokenIds        []string               `protobuf:"bytes,3,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // List of token IDs (as string)
	Amounts         []string               `protobuf:"bytes,4,rep,name=amounts,proto3" json:"amounts,omitempty"`                                        // List of amounts (as string)
	PrivateKey      string                 `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`                // Private key (hex encoded, with or without 0x prefix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnBatchERC1155Request) Reset() {
	*x = BurnBatchERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnBatchERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnBatchERC1155Request) ProtoMessage() {}

func (x *BurnBatchERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnBatchERC1155Request.ProtoReflect.Descriptor instead.
func (*BurnBatchERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{20}
}

func (x *BurnBatchERC1155Request) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BurnBatchERC1155Request) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *BurnBatchERC1155Request) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *BurnBatchERC1155Request) GetAmounts() []string {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *BurnBatchERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type BurnBatchERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Contract address
	AccountAddress  string                 `protobuf:"bytes,3,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`    // Account address
	TokenIds        []string               `protobuf:"bytes,4,rep,name=token_ids,json=tokenIds,proto3" json:"token_ids,omitempty"`                      // Token IDs
	Amounts         []string               `protobuf:"bytes,5,rep,name=amounts,proto3" json:"amounts,omitempty"`                                        // Amounts burned
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnBatchERC1155Response) Reset() {
	*x = BurnBatchERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnBatchERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnBatchERC1155Response) ProtoMessage() {}

func (x *BurnBatchERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnBatchERC1155Response.ProtoReflect.Descriptor instead.
func (*BurnBatchERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{21}
}

func (x *BurnBatchERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *BurnBatchERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *BurnBatchERC1155Response) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *BurnBatchERC1155Response) GetTokenIds() []string {
	if x != nil {
		return x.TokenIds
	}
	return nil
}

func (x *BurnBatchERC1155Response) GetAmounts() []string {
	if x != nil {
		return x.Amounts
	}
	return nil
}

type DeployERC1155Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`                                       // Metadata URI template
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`       // Private key of the deployer
	InitialOwner  string                 `protobuf:"bytes,3,opt,name=initial_owner,json=initialOwner,proto3" json:"initial_owner,omitempty"` // Initial owner address (optional, defaults to deployer)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployERC1155Request) Reset() {
	*x = DeployERC1155Request{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployERC1155Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployERC1155Request) ProtoMessage() {}

func (x *DeployERC1155Request) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployERC1155Request.ProtoReflect.Descriptor instead.
func (*DeployERC1155Request) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{22}
}

func (x *DeployERC1155Request) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DeployERC1155Request) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *DeployERC1155Request) GetInitialOwner() string {
	if x != nil {
		return x.InitialOwner
	}
	return ""
}

type DeployERC1155Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxHash          string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                            // Transaction hash
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Deployed contract address
	DeployerAddress string                 `protobuf:"bytes,3,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"` // Deployer address
	Uri             string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`                                                // Metadata URI template
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployERC1155Response) Reset() {
	*x = DeployERC1155Response{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployERC1155Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployERC1155Response) ProtoMessage() {}

func (x *DeployERC1155Response) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployERC1155Response.ProtoReflect.Descriptor instead.
func (*DeployERC1155Response) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{23}
}

func (x *DeployERC1155Response) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *DeployERC1155Response) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *DeployERC1155Response) GetDeployerAddress() string {
	if x != nil {
		return x.DeployerAddress
	}
	return ""
}

func (x *DeployERC1155Response) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DeployERC1155Request_InitialOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Initial owner address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployERC1155Request_InitialOwner) Reset() {
	*x = DeployERC1155Request_InitialOwner{}
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployERC1155Request_InitialOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployERC1155Request_InitialOwner) ProtoMessage() {}

func (x *DeployERC1155Request_InitialOwner) ProtoReflect() protoreflect.Message {
	mi := &file_erc1155_v1_erc1155_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployERC1155Request_InitialOwner.ProtoReflect.Descriptor instead.
func (*DeployERC1155Request_InitialOwner) Descriptor() ([]byte, []int) {
	return file_erc1155_v1_erc1155_proto_rawDescGZIP(), []int{22, 0}
}

func (x *DeployERC1155Request_InitialOwner) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_erc1155_v1_erc1155_proto protoreflect.FileDescriptor

const file_erc1155_v1_erc1155_proto_rawDesc = "" +
	"\n" +
	"\x18erc1155/v1/erc1155.proto\x12\x0eapi.erc1155.v1\x1a\x1cgoogle/api/annotations.proto\"\x89\x01\n" +
	"\x18GetERC1155BalanceRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x02 \x01(\tR\x0eaccountAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"\xa4\x01\n" +
	"\x19GetERC1155BalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x03 \x01(\tR\x0eaccountAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\"\x84\x01\n" +
	"\x1eGetERC1155BalancesBatchRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x1a\n" +
	"\baccounts\x18\x02 \x03(\tR\baccounts\x12\x1b\n" +
	"\ttoken_ids\x18\x03 \x03(\tR\btokenIds\"\xa1\x01\n" +
	"\x1fGetERC1155BalancesBatchResponse\x12\x1a\n" +
	"\bbalances\x18\x01 \x03(\tR\bbalances\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1a\n" +
	"\baccounts\x18\x03 \x03(\tR\baccounts\x12\x1b\n" +
	"\ttoken_ids\x18\x04 \x03(\tR\btokenIds\"a\n" +
	"\x19GetERC1155TokenURIRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"\x7f\n" +
	"\x1aGetERC1155TokenURIResponse\x12\x1b\n" +
	"\ttoken_uri\x18\x01 \x01(\tR\btokenUri\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"\x9f\x01\n" +
	"\x1eIsApprovedForAllERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x02 \x01(\tR\x0eaccountAddress\x12)\n" +
	"\x10operator_address\x18\x03 \x01(\tR\x0foperatorAddress\"\xbc\x01\n" +
	"\x1fIsApprovedForAllERC1155Response\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x03 \x01(\tR\x0eaccountAddress\x12)\n" +
	"\x10operator_address\x18\x04 \x01(\tR\x0foperatorAddress\"\xf1\x01\n" +
	"\x1aSafeTransferERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1f\n" +
	"\vprivate_key\x18\a \x01(\tR\n" +
	"privateKey\"\xd6\x01\n" +
	"\x1bSafeTransferERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x05 \x01(\tR\atokenId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\"\xfa\x01\n" +
	"\x1fSafeBatchTransferERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x02 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x1b\n" +
	"\ttoken_ids\x18\x04 \x03(\tR\btokenIds\x12\x18\n" +
	"\aamounts\x18\x05 \x03(\tR\aamounts\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x1f\n" +
	"\vprivate_key\x18\a \x01(\tR\n" +
	"privateKey\"\xdf\x01\n" +
	" SafeBatchTransferERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x1b\n" +
	"\ttoken_ids\x18\x05 \x03(\tR\btokenIds\x12\x18\n" +
	"\aamounts\x18\x06 \x03(\tR\aamounts\"\xb4\x01\n" +
	"\x1fSetApprovalForAllERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12)\n" +
	"\x10operator_address\x18\x02 \x01(\tR\x0foperatorAddress\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\"\xd2\x01\n" +
	" SetApprovalForAllERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12#\n" +
	"\rowner_address\x18\x03 \x01(\tR\fownerAddress\x12)\n" +
	"\x10operator_address\x18\x04 \x01(\tR\x0foperatorAddress\x12\x1a\n" +
	"\bapproved\x18\x05 \x01(\bR\bapproved\"\xc6\x01\n" +
	"\x12MintERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\tR\n" +
	"privateKey\"\xab\x01\n" +
	"\x13MintERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"\xcf\x01\n" +
	"\x17MintBatchERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x1b\n" +
	"\ttoken_ids\x18\x03 \x03(\tR\btokenIds\x12\x18\n" +
	"\aamounts\x18\x04 \x03(\tR\aamounts\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\tR\n" +
	"privateKey\"\xb4\x01\n" +
	"\x18MintBatchERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x1b\n" +
	"\ttoken_ids\x18\x04 \x03(\tR\btokenIds\x12\x18\n" +
	"\aamounts\x18\x05 \x03(\tR\aamounts\"\xbc\x01\n" +
	"\x12BurnERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x02 \x01(\tR\x0eaccountAddress\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\"\xb5\x01\n" +
	"\x13BurnERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x03 \x01(\tR\x0eaccountAddress\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"\xc5\x01\n" +
	"\x17BurnBatchERC1155Request\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x02 \x01(\tR\x0eaccountAddress\x12\x1b\n" +
	"\ttoken_ids\x18\x03 \x03(\tR\btokenIds\x12\x18\n" +
	"\aamounts\x18\x04 \x03(\tR\aamounts\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\"\xbe\x01\n" +
	"\x18BurnBatchERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12'\n" +
	"\x0faccount_address\x18\x03 \x01(\tR\x0eaccountAddress\x12\x1b\n" +
	"\ttoken_ids\x18\x04 \x03(\tR\btokenIds\x12\x18\n" +
	"\aamounts\x18\x05 \x03(\tR\aamounts\"\x98\x01\n" +
	"\x14DeployERC1155Request\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12#\n" +
	"\rinitial_owner\x18\x03 \x01(\tR\finitialOwner\x1a(\n" +
	"\fInitialOwner\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x98\x01\n" +
	"\x15DeployERC1155Response\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12)\n" +
	"\x10deployer_address\x18\x03 \x01(\tR\x0fdeployerAddress\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri2\x81\x0e\n" +
	"\aERC1155\x12\x89\x01\n" +
	"\x11GetERC1155Balance\x12(.api.erc1155.v1.GetERC1155BalanceRequest\x1a).api.erc1155.v1.GetERC1155BalanceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/erc1155/balance\x12\xa1\x01\n" +
	"\x17GetERC1155BalancesBatch\x12..api.erc1155.v1.GetERC1155BalancesBatchRequest\x1a/.api.erc1155.v1.GetERC1155BalancesBatchResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/erc1155/balance-batch\x12\x8e\x01\n" +
	"\x12GetERC1155TokenURI\x12).api.erc1155.v1.GetERC1155TokenURIRequest\x1a*.api.erc1155.v1.GetERC1155TokenURIResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/erc1155/token-uri\x12\xa7\x01\n" +
	"\x17IsApprovedForAllERC1155\x12..api.erc1155.v1.IsApprovedForAllERC1155Request\x1a/.api.erc1155.v1.IsApprovedForAllERC1155Response\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/erc1155/is-approved-for-all\x12\x98\x01\n" +
	"\x13SafeTransferERC1155\x12*.api.erc1155.v1.SafeTransferERC1155Request\x1a+.api.erc1155.v1.SafeTransferERC1155Response\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/erc1155/safe-transfer\x12\xad\x01\n" +
	"\x18SafeBatchTransferERC1155\x12/.api.erc1155.v1.SafeBatchTransferERC1155Request\x1a0.api.erc1155.v1.SafeBatchTransferERC1155Response\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/erc1155/safe-batch-transfer\x12\xae\x01\n" +
	"\x18SetApprovalForAllERC1155\x12/.api.erc1155.v1.SetApprovalForAllERC1155Request\x1a0.api.erc1155.v1.SetApprovalForAllERC1155Response\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/erc1155/set-approval-for-all\x12w\n" +
	"\vMintERC1155\x12\".api.erc1155.v1.MintERC1155Request\x1a#.api.erc1155.v1.MintERC1155Response\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/erc1155/mint\x12\x8c\x01\n" +
	"\x10MintBatchERC1155\x12'.api.erc1155.v1.MintBatchERC1155Request\x1a(.api.erc1155.v1.MintBatchERC1155Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/erc1155/mint-batch\x12w\n" +
	"\vBurnERC1155\x12\".api.erc1155.v1.BurnERC1155Request\x1a#.api.erc1155.v1.BurnERC1155Response\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/erc1155/burn\x12\x8c\x01\n" +
	"\x10BurnBatchERC1155\x12'.api.erc1155.v1.BurnBatchERC1155Request\x1a(.api.erc1155.v1.BurnBatchERC1155Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/erc1155/burn-batch\x12\x7f\n" +
	"\rDeployERC1155\x12$.api.erc1155.v1.DeployERC1155Request\x1a%.api.erc1155.v1.DeployERC1155Response\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/erc1155/deployB:\n" +
	"\x0eapi.erc1155.v1P\x01Z&eth-contract-service/api/erc1155/v1;v1b\x06proto3"

var (
	file_erc1155_v1_erc1155_proto_rawDescOnce sync.Once
	file_erc1155_v1_erc1155_proto_rawDescData []byte
)

func file_erc1155_v1_erc1155_proto_rawDescGZIP() []byte {
	file_erc1155_v1_erc1155_proto_rawDescOnce.Do(func() {
		file_erc1155_v1_erc1155_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_erc1155_v1_erc1155_proto_rawDesc), len(file_erc1155_v1_erc1155_proto_rawDesc)))
	})
	return file_erc1155_v1_erc1155_proto_rawDescData
}

var file_erc1155_v1_erc1155_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_erc1155_v1_erc1155_proto_goTypes = []any{
	(*GetERC1155BalanceRequest)(nil),          // 0: api.erc1155.v1.GetERC1155BalanceRequest
	(*GetERC1155BalanceResponse)(nil),         // 1: api.erc1155.v1.GetERC1155BalanceResponse
	(*GetERC1155BalancesBatchRequest)(nil),    // 2: api.erc1155.v1.GetERC1155BalancesBatchRequest
	(*GetERC1155BalancesBatchResponse)(nil),   // 3: api.erc1155.v1.GetERC1155BalancesBatchResponse
	(*GetERC1155TokenURIRequest)(nil),         // 4: api.erc1155.v1.GetERC1155TokenURIRequest
	(*GetERC1155TokenURIResponse)(nil),        // 5: api.erc1155.v1.GetERC1155TokenURIResponse
	(*IsApprovedForAllERC1155Request)(nil),    // 6: api.erc1155.v1.IsApprovedForAllERC1155Request
	(*IsApprovedForAllERC1155Response)(nil),   // 7: api.erc1155.v1.IsApprovedForAllERC1155Response
	(*SafeTransferERC1155Request)(nil),        // 8: api.erc1155.v1.SafeTransferERC1155Request
	(*SafeTransferERC1155Response)(nil),       // 9: api.erc1155.v1.SafeTransferERC1155Response
	(*SafeBatchTransferERC1155Request)(nil),   // 10: api.erc1155.v1.SafeBatchTransferERC1155Request
	(*SafeBatchTransferERC1155Response)(nil),  // 11: api.erc1155.v1.SafeBatchTransferERC1155Response
	(*SetApprovalForAllERC1155Request)(nil),   // 12: api.erc1155.v1.SetApprovalForAllERC1155Request
	(*SetApprovalForAllERC1155Response)(nil),  // 13: api.erc1155.v1.SetApprovalForAllERC1155Response
	(*MintERC1155Request)(nil),                // 14: api.erc1155.v1.MintERC1155Request
	(*MintERC1155Response)(nil),               // 15: api.erc1155.v1.MintERC1155Response
	(*MintBatchERC1155Request)(nil),           // 16: api.erc1155.v1.MintBatchERC1155Request
	(*MintBatchERC1155Response)(nil),          // 17: api.erc1155.v1.MintBatchERC1155Response
	(*BurnERC1155Request)(nil),                // 18: api.erc1155.v1.BurnERC1155Request
	(*BurnERC1155Response)(nil),               // 19: api.erc1155.v1.BurnERC1155Response
	(*BurnBatchERC1155Request)(nil),           // 20: api.erc1155.v1.BurnBatchERC1155Request
	(*BurnBatchERC1155Response)(nil),          // 21: api.erc1155.v1.BurnBatchERC1155Response
	(*DeployERC1155Request)(nil),              // 22: api.erc1155.v1.DeployERC1155Request
	(*DeployERC1155Response)(nil),             // 23: api.erc1155.v1.DeployERC1155Response
	(*DeployERC1155Request_InitialOwner)(nil), // 24: api.erc1155.v1.DeployERC1155Request.InitialOwner
}
var file_erc1155_v1_erc1155_proto_depIdxs = []int32{
	0,  // 0: api.erc1155.v1.ERC1155.GetERC1155Balance:input_type -> api.erc1155.v1.GetERC1155BalanceRequest
	2,  // 1: api.erc1155.v1.ERC1155.GetERC1155BalancesBatch:input_type -> api.erc1155.v1.GetERC1155BalancesBatchRequest
	4,  // 2: api.erc1155.v1.ERC1155.GetERC1155TokenURI:input_type -> api.erc1155.v1.GetERC1155TokenURIRequest
	6,  // 3: api.erc1155.v1.ERC1155.IsApprovedForAllERC1155:input_type -> api.erc1155.v1.IsApprovedForAllERC1155Request
	8,  // 4: api.erc1155.v1.ERC1155.SafeTransferERC1155:input_type -> api.erc1155.v1.SafeTransferERC1155Request
	10, // 5: api.erc1155.v1.ERC1155.SafeBatchTransferERC1155:input_type -> api.erc1155.v1.SafeBatchTransferERC1155Request
	12, // 6: api.erc1155.v1.ERC1155.SetApprovalForAllERC1155:input_type -> api.erc1155.v1.SetApprovalForAllERC1155Request
	14, // 7: api.erc1155.v1.ERC1155.MintERC1155:input_type -> api.erc1155.v1.MintERC1155Request
	16, // 8: api.erc1155.v1.ERC1155.MintBatchERC1155:input_type -> api.erc1155.v1.MintBatchERC1155Request
	18, // 9: api.erc1155.v1.ERC1155.BurnERC1155:input_type -> api.erc1155.v1.BurnERC1155Request
	20, // 10: api.erc1155.v1.ERC1155.BurnBatchERC1155:input_type -> api.erc1155.v1.BurnBatchERC1155Request
	22, // 11: api.erc1155.v1.ERC1155.DeployERC1155:input_type -> api.erc1155.v1.DeployERC1155Request
	1,  // 12: api.erc1155.v1.ERC1155.GetERC1155Balance:output_type -> api.erc1155.v1.GetERC1155BalanceResponse
	3,  // 13: api.erc1155.v1.ERC1155.GetERC1155BalancesBatch:output_type -> api.erc1155.v1.GetERC1155BalancesBatchResponse
	5,  // 14: api.erc1155.v1.ERC1155.GetERC1155TokenURI:output_type -> api.erc1155.v1.GetERC1155TokenURIResponse
	7,  // 15: api.erc1155.v1.ERC1155.IsApprovedForAllERC1155:output_type -> api.erc1155.v1.IsApprovedForAllERC1155Response
	9,  // 16: api.erc1155.v1.ERC1155.SafeTransferERC1155:output_type -> api.erc1155.v1.SafeTransferERC1155Response
	11, // 17: api.erc1155.v1.ERC1155.SafeBatchTransferERC1155:output_type -> api.erc1155.v1.SafeBatchTransferERC1155Response
	13, // 18: api.erc1155.v1.ERC1155.SetApprovalForAllERC1155:output_type -> api.erc1155.v1.SetApprovalForAllERC1155Response
	15, // 19: api.erc1155.v1.ERC1155.MintERC1155:output_type -> api.erc1155.v1.MintERC1155Response
	17, // 20: api.erc1155.v1.ERC1155.MintBatchERC1155:output_type -> api.erc1155.v1.MintBatchERC1155Response
	19, // 21: api.erc1155.v1.ERC1155.BurnERC1155:output_type -> api.erc1155.v1.BurnERC1155Response
	21, // 22: api.erc1155.v1.ERC1155.BurnBatchERC1155:output_type -> api.erc1155.v1.BurnBatchERC1155Response
	23, // 23: api.erc1155.v1.ERC1155.DeployERC1155:output_type -> api.erc1155.v1.DeployERC1155Response
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_erc1155_v1_erc1155_proto_init() }
func file_erc1155_v1_erc1155_proto_init() {
	if File_erc1155_v1_erc1155_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_erc1155_v1_erc1155_proto_rawDesc), len(file_erc1155_v1_erc1155_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_erc1155_v1_erc1155_proto_goTypes,
		DependencyIndexes: file_erc1155_v1_erc1155_proto_depIdxs,
		MessageInfos:      file_erc1155_v1_erc1155_proto_msgTypes,
	}.Build()
	File_erc1155_v1_erc1155_proto = out.File
	file_erc1155_v1_erc1155_proto_goTypes = nil
	file_erc1155_v1_erc1155_proto_depIdxs = nil
}
