// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: erc1155/v1/erc1155.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ERC1155_GetERC1155Balance_FullMethodName        = "/api.erc1155.v1.ERC1155/GetERC1155Balance"
	ERC1155_GetERC1155BalancesBatch_FullMethodName  = "/api.erc1155.v1.ERC1155/GetERC1155BalancesBatch"
	ERC1155_GetERC1155TokenURI_FullMethodName       = "/api.erc1155.v1.ERC1155/GetERC1155TokenURI"
	ERC1155_IsApprovedForAllERC1155_FullMethodName  = "/api.erc1155.v1.ERC1155/IsApprovedForAllERC1155"
	ERC1155_SafeTransferERC1155_FullMethodName      = "/api.erc1155.v1.ERC1155/SafeTransferERC1155"
	ERC1155_SafeBatchTransferERC1155_FullMethodName = "/api.erc1155.v1.ERC1155/SafeBatchTransferERC1155"
	ERC1155_SetApprovalForAllERC1155_FullMethodName = "/api.erc1155.v1.ERC1155/SetApprovalForAllERC1155"
	ERC1155_MintERC1155_FullMethodName              = "/api.erc1155.v1.ERC1155/MintERC1155"
	ERC1155_MintBatchERC1155_FullMethodName         = "/api.erc1155.v1.ERC1155/MintBatchERC1155"
	ERC1155_BurnERC1155_FullMethodName              = "/api.erc1155.v1.ERC1155/BurnERC1155"
	ERC1155_BurnBatchERC1155_FullMethodName         = "/api.erc1155.v1.ERC1155/BurnBatchERC1155"
	ERC1155_DeployERC1155_FullMethodName            = "/api.erc1155.v1.ERC1155/DeployERC1155"
)

// ERC1155Client is the client API for ERC1155 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ERC1155 service provides ERC1155 (Multi-Token) token interaction endpoints
type ERC1155Client interface {
	// GetERC1155Balance returns the balance of an address for a specific token ID
	GetERC1155Balance(ctx context.Context, in *GetERC1155BalanceRequest, opts ...grpc.CallOption) (*GetERC1155BalanceResponse, error)
	// GetERC1155BalancesBatch returns the balance of multiple addresses for multiple token IDs
	GetERC1155BalancesBatch(ctx context.Context, in *GetERC1155BalancesBatchRequest, opts ...grpc.CallOption) (*GetERC1155BalancesBatchResponse, error)
	// GetERC1155TokenURI returns the URI for a specific token ID
	GetERC1155TokenURI(ctx context.Context, in *GetERC1155TokenURIRequest, opts ...grpc.CallOption) (*GetERC1155TokenURIResponse, error)
	// IsApprovedForAllERC1155 checks if an operator is approved for all tokens of an owner
	IsApprovedForAllERC1155(ctx context.Context, in *IsApprovedForAllERC1155Request, opts ...grpc.CallOption) (*IsApprovedForAllERC1155Response, error)
	// SafeTransferERC1155 transfers an ERC1155 token from one address to another
	SafeTransferERC1155(ctx context.Context, in *SafeTransferERC1155Request, opts ...grpc.CallOption) (*SafeTransferERC1155Response, error)
	// SafeBatchTransferERC1155 safely transfers multiple ERC1155 tokens
	SafeBatchTransferERC1155(ctx context.Context, in *SafeBatchTransferERC1155Request, opts ...grpc.CallOption) (*SafeBatchTransferERC1155Response, error)
	// SetApprovalForAllERC1155 enables or disables approval for a third party ("operator") to manage all tokens
	SetApprovalForAllERC1155(ctx context.Context, in *SetApprovalForAllERC1155Request, opts ...grpc.CallOption) (*SetApprovalForAllERC1155Response, error)
	// MintERC1155 mints new ERC1155 tokens
	MintERC1155(ctx context.Context, in *MintERC1155Request, opts ...grpc.CallOption) (*MintERC1155Response, error)
	// MintBatchERC1155 mints multiple ERC1155 tokens
	MintBatchERC1155(ctx context.Context, in *MintBatchERC1155Request, opts ...grpc.CallOption) (*MintBatchERC1155Response, error)
	// BurnERC1155 burns ERC1155 tokens
	BurnERC1155(ctx context.Context, in *BurnERC1155Request, opts ...grpc.CallOption) (*BurnERC1155Response, error)
	// BurnBatchERC1155 burns multiple ERC1155 tokens
	BurnBatchERC1155(ctx context.Context, in *BurnBatchERC1155Request, opts ...grpc.CallOption) (*BurnBatchERC1155Response, error)
	// DeployERC1155 deploys a new ERC1155 token contract
	DeployERC1155(ctx context.Context, in *DeployERC1155Request, opts ...grpc.CallOption) (*DeployERC1155Response, error)
}

type eRC1155Client struct {
	cc grpc.ClientConnInterface
}

func NewERC1155Client(cc grpc.ClientConnInterface) ERC1155Client {
	return &eRC1155Client{cc}
}

func (c *eRC1155Client) GetERC1155Balance(ctx context.Context, in *GetERC1155BalanceRequest, opts ...grpc.CallOption) (*GetERC1155BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetERC1155BalanceResponse)
	err := c.cc.Invoke(ctx, ERC1155_GetERC1155Balance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) GetERC1155BalancesBatch(ctx context.Context, in *GetERC1155BalancesBatchRequest, opts ...grpc.CallOption) (*GetERC1155BalancesBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetERC1155BalancesBatchResponse)
	err := c.cc.Invoke(ctx, ERC1155_GetERC1155BalancesBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) GetERC1155TokenURI(ctx context.Context, in *GetERC1155TokenURIRequest, opts ...grpc.CallOption) (*GetERC1155TokenURIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetERC1155TokenURIResponse)
	err := c.cc.Invoke(ctx, ERC1155_GetERC1155TokenURI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) IsApprovedForAllERC1155(ctx context.Context, in *IsApprovedForAllERC1155Request, opts ...grpc.CallOption) (*IsApprovedForAllERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsApprovedForAllERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_IsApprovedForAllERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) SafeTransferERC1155(ctx context.Context, in *SafeTransferERC1155Request, opts ...grpc.CallOption) (*SafeTransferERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafeTransferERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_SafeTransferERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) SafeBatchTransferERC1155(ctx context.Context, in *SafeBatchTransferERC1155Request, opts ...grpc.CallOption) (*SafeBatchTransferERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SafeBatchTransferERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_SafeBatchTransferERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) SetApprovalForAllERC1155(ctx context.Context, in *SetApprovalForAllERC1155Request, opts ...grpc.CallOption) (*SetApprovalForAllERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetApprovalForAllERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_SetApprovalForAllERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) MintERC1155(ctx context.Context, in *MintERC1155Request, opts ...grpc.CallOption) (*MintERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_MintERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) MintBatchERC1155(ctx context.Context, in *MintBatchERC1155Request, opts ...grpc.CallOption) (*MintBatchERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintBatchERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_MintBatchERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) BurnERC1155(ctx context.Context, in *BurnERC1155Request, opts ...grpc.CallOption) (*BurnERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BurnERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_BurnERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) BurnBatchERC1155(ctx context.Context, in *BurnBatchERC1155Request, opts ...grpc.CallOption) (*BurnBatchERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BurnBatchERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_BurnBatchERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eRC1155Client) DeployERC1155(ctx context.Context, in *DeployERC1155Request, opts ...grpc.CallOption) (*DeployERC1155Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployERC1155Response)
	err := c.cc.Invoke(ctx, ERC1155_DeployERC1155_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ERC1155Server is the server API for ERC1155 service.
// All implementations must embed UnimplementedERC1155Server
// for forward compatibility.
//
// ERC1155 service provides ERC1155 (Multi-Token) token interaction endpoints
type ERC1155Server interface {
	// GetERC1155Balance returns the balance of an address for a specific token ID
	GetERC1155Balance(context.Context, *GetERC1155BalanceRequest) (*GetERC1155BalanceResponse, error)
	// GetERC1155BalancesBatch returns the balance of multiple addresses for multiple token IDs
	GetERC1155BalancesBatch(context.Context, *GetERC1155BalancesBatchRequest) (*GetERC1155BalancesBatchResponse, error)
	// GetERC1155TokenURI returns the URI for a specific token ID
	GetERC1155TokenURI(context.Context, *GetERC1155TokenURIRequest) (*GetERC1155TokenURIResponse, error)
	// IsApprovedForAllERC1155 checks if an operator is approved for all tokens of an owner
	IsApprovedForAllERC1155(context.Context, *IsApprovedForAllERC1155Request) (*IsApprovedForAllERC1155Response, error)
	// SafeTransferERC1155 transfers an ERC1155 token from one address to another
	SafeTransferERC1155(context.Context, *SafeTransferERC1155Request) (*SafeTransferERC1155Response, error)
	// SafeBatchTransferERC1155 safely transfers multiple ERC1155 tokens
	SafeBatchTransferERC1155(context.Context, *SafeBatchTransferERC1155Request) (*SafeBatchTransferERC1155Response, error)
	// SetApprovalForAllERC1155 enables or disables approval for a third party ("operator") to manage all tokens
	SetApprovalForAllERC1155(context.Context, *SetApprovalForAllERC1155Request) (*SetApprovalForAllERC1155Response, error)
	// MintERC1155 mints new ERC1155 tokens
	MintERC1155(context.Context, *MintERC1155Request) (*MintERC1155Response, error)
	// MintBatchERC1155 mints multiple ERC1155 tokens
	MintBatchERC1155(context.Context, *MintBatchERC1155Request) (*MintBatchERC1155Response, error)
	// BurnERC1155 burns ERC1155 tokens
	BurnERC1155(context.Context, *BurnERC1155Request) (*BurnERC1155Response, error)
	// BurnBatchERC1155 burns multiple ERC1155 tokens
	BurnBatchERC1155(context.Context, *BurnBatchERC1155Request) (*BurnBatchERC1155Response, error)
	// DeployERC1155 deploys a new ERC1155 token contract
	DeployERC1155(context.Context, *DeployERC1155Request) (*DeployERC1155Response, error)
	mustEmbedUnimplementedERC1155Server()
}

// UnimplementedERC1155Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedERC1155Server struct{}

func (UnimplementedERC1155Server) GetERC1155Balance(context.Context, *GetERC1155BalanceRequest) (*GetERC1155BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetERC1155Balance not implemented")
}
func (UnimplementedERC1155Server) GetERC1155BalancesBatch(context.Context, *GetERC1155BalancesBatchRequest) (*GetERC1155BalancesBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetERC1155BalancesBatch not implemented")
}
func (UnimplementedERC1155Server) GetERC1155TokenURI(context.Context, *GetERC1155TokenURIRequest) (*GetERC1155TokenURIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetERC1155TokenURI not implemented")
}
func (UnimplementedERC1155Server) IsApprovedForAllERC1155(context.Context, *IsApprovedForAllERC1155Request) (*IsApprovedForAllERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method IsApprovedForAllERC1155 not implemented")
}
func (UnimplementedERC1155Server) SafeTransferERC1155(context.Context, *SafeTransferERC1155Request) (*SafeTransferERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SafeTransferERC1155 not implemented")
}
func (UnimplementedERC1155Server) SafeBatchTransferERC1155(context.Context, *SafeBatchTransferERC1155Request) (*SafeBatchTransferERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SafeBatchTransferERC1155 not implemented")
}
func (UnimplementedERC1155Server) SetApprovalForAllERC1155(context.Context, *SetApprovalForAllERC1155Request) (*SetApprovalForAllERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetApprovalForAllERC1155 not implemented")
}
func (UnimplementedERC1155Server) MintERC1155(context.Context, *MintERC1155Request) (*MintERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MintERC1155 not implemented")
}
func (UnimplementedERC1155Server) MintBatchERC1155(context.Context, *MintBatchERC1155Request) (*MintBatchERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method MintBatchERC1155 not implemented")
}
func (UnimplementedERC1155Server) BurnERC1155(context.Context, *BurnERC1155Request) (*BurnERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method BurnERC1155 not implemented")
}
func (UnimplementedERC1155Server) BurnBatchERC1155(context.Context, *BurnBatchERC1155Request) (*BurnBatchERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method BurnBatchERC1155 not implemented")
}
func (UnimplementedERC1155Server) DeployERC1155(context.Context, *DeployERC1155Request) (*DeployERC1155Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployERC1155 not implemented")
}
func (UnimplementedERC1155Server) mustEmbedUnimplementedERC1155Server() {}
func (UnimplementedERC1155Server) testEmbeddedByValue()                 {}

// UnsafeERC1155Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ERC1155Server will
// result in compilation errors.
type UnsafeERC1155Server interface {
	mustEmbedUnimplementedERC1155Server()
}

func RegisterERC1155Server(s grpc.ServiceRegistrar, srv ERC1155Server) {
	// If the following call panics, it indicates UnimplementedERC1155Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ERC1155_ServiceDesc, srv)
}

func _ERC1155_GetERC1155Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetERC1155BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).GetERC1155Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_GetERC1155Balance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).GetERC1155Balance(ctx, req.(*GetERC1155BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_GetERC1155BalancesBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetERC1155BalancesBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).GetERC1155BalancesBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_GetERC1155BalancesBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).GetERC1155BalancesBatch(ctx, req.(*GetERC1155BalancesBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_GetERC1155TokenURI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetERC1155TokenURIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).GetERC1155TokenURI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_GetERC1155TokenURI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).GetERC1155TokenURI(ctx, req.(*GetERC1155TokenURIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_IsApprovedForAllERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsApprovedForAllERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).IsApprovedForAllERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_IsApprovedForAllERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).IsApprovedForAllERC1155(ctx, req.(*IsApprovedForAllERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_SafeTransferERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafeTransferERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).SafeTransferERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_SafeTransferERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).SafeTransferERC1155(ctx, req.(*SafeTransferERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_SafeBatchTransferERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SafeBatchTransferERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).SafeBatchTransferERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_SafeBatchTransferERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).SafeBatchTransferERC1155(ctx, req.(*SafeBatchTransferERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_SetApprovalForAllERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetApprovalForAllERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).SetApprovalForAllERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_SetApprovalForAllERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).SetApprovalForAllERC1155(ctx, req.(*SetApprovalForAllERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_MintERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).MintERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_MintERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).MintERC1155(ctx, req.(*MintERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_MintBatchERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintBatchERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).MintBatchERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_MintBatchERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).MintBatchERC1155(ctx, req.(*MintBatchERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_BurnERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BurnERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).BurnERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_BurnERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).BurnERC1155(ctx, req.(*BurnERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_BurnBatchERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BurnBatchERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).BurnBatchERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_BurnBatchERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).BurnBatchERC1155(ctx, req.(*BurnBatchERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ERC1155_DeployERC1155_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployERC1155Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ERC1155Server).DeployERC1155(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ERC1155_DeployERC1155_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ERC1155Server).DeployERC1155(ctx, req.(*DeployERC1155Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ERC1155_ServiceDesc is the grpc.ServiceDesc for ERC1155 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ERC1155_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.erc1155.v1.ERC1155",
	HandlerType: (*ERC1155Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetERC1155Balance",
			Handler:    _ERC1155_GetERC1155Balance_Handler,
		},
		{
			MethodName: "GetERC1155BalancesBatch",
			Handler:    _ERC1155_GetERC1155BalancesBatch_Handler,
		},
		{
			MethodName: "GetERC1155TokenURI",
			Handler:    _ERC1155_GetERC1155TokenURI_Handler,
		},
		{
			MethodName: "IsApprovedForAllERC1155",
			Handler:    _ERC1155_IsApprovedForAllERC1155_Handler,
		},
		{
			MethodName: "SafeTransferERC1155",
			Handler:    _ERC1155_SafeTransferERC1155_Handler,
		},
		{
			MethodName: "SafeBatchTransferERC1155",
			Handler:    _ERC1155_SafeBatchTransferERC1155_Handler,
		},
		{
			MethodName: "SetApprovalForAllERC1155",
			Handler:    _ERC1155_SetApprovalForAllERC1155_Handler,
		},
		{
			MethodName: "MintERC1155",
			Handler:    _ERC1155_MintERC1155_Handler,
		},
		{
			MethodName: "MintBatchERC1155",
			Handler:    _ERC1155_MintBatchERC1155_Handler,
		},
		{
			MethodName: "BurnERC1155",
			Handler:    _ERC1155_BurnERC1155_Handler,
		},
		{
			MethodName: "BurnBatchERC1155",
			Handler:    _ERC1155_BurnBatchERC1155_Handler,
		},
		{
			MethodName: "DeployERC1155",
			Handler:    _ERC1155_DeployERC1155_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "erc1155/v1/erc1155.proto",
}
